// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f3ae1a0d-0d83-40a2-ab22-f70ce723ea81";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCutoffChange();
void onFlowChange();
void onTimerChange();
void onWateringChange();

float moisture;
int cutoff;
int flow;
CloudSchedule timer;
bool watering;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(moisture, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(cutoff, READWRITE, ON_CHANGE, onCutoffChange);
  ArduinoCloud.addProperty(flow, READWRITE, ON_CHANGE, onFlowChange);
  ArduinoCloud.addProperty(timer, READWRITE, ON_CHANGE, onTimerChange);
  ArduinoCloud.addProperty(watering, READWRITE, ON_CHANGE, onWateringChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
